export const MINI_GAMES = {
  free: [
    {
      id: "this-or-that",
      title: "This or That",
      description: "Quick-fire preference questions to learn about each other",
      icon: "Zap" as const,
      questions: [
        { question: "Coffee or Tea?", options: ["Coffee", "Tea"] },
        { question: "Beach or Mountains?", options: ["Beach", "Mountains"] },
        { question: "Morning person or Night owl?", options: ["Morning", "Night"] },
        { question: "Cooking together or Dining out?", options: ["Cooking", "Dining"] },
        { question: "Action movie or Romance movie?", options: ["Action", "Romance"] },
        { question: "Stay in or Go out?", options: ["Stay in", "Go out"] },
        { question: "Hot weather or Cold weather?", options: ["Hot", "Cold"] },
        { question: "Text or Call?", options: ["Text", "Call"] },
        { question: "Dogs or Cats?", options: ["Dogs", "Cats"] },
        { question: "Pizza or Pasta?", options: ["Pizza", "Pasta"] },
      ],
    },
  ],
  premium: [
    {
      id: "memory-match",
      title: "Memory Match",
      description: "Test how well you remember each other's favorites",
      icon: "Brain" as const,
      questions: [
        "What's your partner's favorite color?",
        "What's their dream vacation destination?",
        "What's their comfort food?",
        "What's their biggest fear?",
        "What's their proudest achievement?",
        "What's their favorite childhood memory?",
        "What do they do to relax after a stressful day?",
        "What's their love language?",
        "What's a hidden talent they have?",
        "What's something they've always wanted to try?",
      ],
    },
    {
      id: "guess-their-answer",
      title: "Guess Their Answer",
      description: "Predict how your partner would respond to various scenarios",
      icon: "HelpCircle" as const,
      scenarios: [
        "If you won $1 million, what would be the first thing you'd buy?",
        "If you could have dinner with anyone, living or dead, who would it be?",
        "What superpower would you choose?",
        "What's your ideal weekend?",
        "If you could change one thing about your past, what would it be?",
        "What's your guilty pleasure?",
        "What's the most romantic gesture someone could do for you?",
        "If you could live anywhere in the world, where would it be?",
        "What's your biggest relationship pet peeve?",
        "What makes you feel most loved?",
      ],
    },
    {
      id: "truth-tiles",
      title: "Truth Tiles",
      description: "Tap tiles to reveal fun facts and truths about relationships",
      icon: "Grid3x3" as const,
      tiles: [
        { category: "First", prompt: "Share your first impression of your partner" },
        { category: "Dream", prompt: "What's a dream you have for your relationship?" },
        { category: "Gratitude", prompt: "What are you grateful for about your partner?" },
        { category: "Memory", prompt: "Share your favorite memory together" },
        { category: "Future", prompt: "Where do you see yourselves in 5 years?" },
        { category: "Challenge", prompt: "What's been your biggest challenge as a couple?" },
        { category: "Laugh", prompt: "Share a funny moment from your relationship" },
        { category: "Growth", prompt: "How has your partner helped you grow?" },
        { category: "Love", prompt: "When did you know you were in love?" },
        { category: "Support", prompt: "How does your partner support you?" },
        { category: "Adventure", prompt: "What adventure do you want to go on together?" },
        { category: "Tradition", prompt: "What's a tradition you want to create together?" },
      ],
    },
    {
      id: "emotional-bingo",
      title: "Emotional Bingo",
      description: "Complete emotional connection challenges together",
      icon: "Heart" as const,
      challenges: [
        "Share something you've never told anyone",
        "Give your partner 5 genuine compliments",
        "Talk about a time you felt vulnerable",
        "Describe your ideal date night",
        "Share a fear you have about the future",
        "Tell your partner why you're proud of them",
        "Discuss a childhood memory that shaped you",
        "Share something you need more of in the relationship",
        "Talk about what makes you feel secure",
        "Describe how your partner makes you better",
        "Share a goal you need support with",
        "Talk about your love language",
        "Discuss your biggest dream together",
        "Share what intimacy means to you",
        "Talk about a conflict and how you can grow from it",
      ],
    },
  ],
};

export const CONVERSATION_PACKS = {
  free: [
    "What's something new you learned about yourself recently?",
    "What makes you feel most loved by me?",
    "What's a goal you have for us as a couple?",
    "What's your happiest memory with me?",
    "How can I support you better this week?",
  ],
  premium: {
    trust: [
      "Is there anything you've been hesitant to share with me? I'm here to listen.",
      "What does trust mean to you in a relationship?",
      "Have I ever done something that made you question my intentions?",
      "What would help you feel more secure in our relationship?",
      "Is there a past hurt that still affects how you trust people?",
      "How can I show you that you can rely on me?",
      "What's something you need from me to feel completely safe?",
      "Are there any boundaries we should discuss or revisit?",
      "What would rebuilding trust look like if it were ever broken?",
      "How do you want me to handle situations where we disagree?",
    ],
    intimacy: [
      "When do you feel most emotionally connected to me?",
      "What's a vulnerable part of yourself you want me to understand better?",
      "How do you experience emotional intimacy differently than physical intimacy?",
      "What makes you feel truly seen and understood by me?",
      "Is there a part of your life where you wish I was more involved?",
      "What's a fantasy or dream you've been too shy to share?",
      "How can we create more moments of deep connection?",
      "What does emotional safety look like for you?",
      "When do you feel most distant from me, and why?",
      "How can I help you feel more comfortable being vulnerable?",
    ],
    sex: [
      "What makes you feel desired and attractive?",
      "Is there something you've wanted to try but haven't brought up?",
      "How do you feel about our physical connection right now?",
      "What's something I do that turns you on?",
      "How can we make intimacy more exciting or meaningful?",
      "What does great sex mean to you?",
      "Is there anything that makes you feel uncomfortable or disconnected?",
      "How often would you ideally like to be intimate?",
      "What's a fantasy you have about us?",
      "How can I help you feel more confident in our intimacy?",
    ],
    healing: [
      "Is there a past conflict between us that still hurts?",
      "What's something I've done that I haven't apologized for?",
      "How can I help you heal from something in your past?",
      "What do you need from me when you're hurting?",
      "Are there any resentments you're holding onto?",
      "What would help you forgive me for past mistakes?",
      "Is there something I don't understand about your pain?",
      "How can we move forward from difficult times together?",
      "What does healing look like for you in our relationship?",
      "What's a conversation we've been avoiding that we need to have?",
    ],
    childhood: [
      "What did love look like in your family growing up?",
      "How did your parents' relationship influence your view of love?",
      "What childhood experience still affects how you show love?",
      "Did you feel emotionally safe as a child?",
      "How did your family handle conflict?",
      "What's a childhood wound that still impacts you today?",
      "What patterns from your upbringing do you see in our relationship?",
      "How did you learn about communication and affection?",
      "What's something from your childhood you want to heal?",
      "How can understanding your past help us build a better future?",
    ],
  },
};

export const CONFLICT_REPAIR_SCRIPTS = {
  free: [
    {
      issue: "General conflict",
      script: "I care about us, and I want to work through this together. Can we take a moment to understand each other's perspective?",
    },
  ],
  premium: {
    jealousy: {
      title: "Jealousy Issues",
      icon: "AlertTriangle" as const,
      steps: [
        {
          step: "Acknowledge the feeling",
          script: "I'm feeling jealous about [specific situation]. I know it might not be rational, but I want to share what's going on in my mind.",
        },
        {
          step: "Express your need",
          script: "What I really need right now is reassurance. Can you help me understand [the situation] from your perspective?",
        },
        {
          step: "Listen actively",
          script: "I'm listening. Help me understand what happened and how you felt about it.",
        },
        {
          step: "Rebuild security",
          script: "What can we both do to help me feel more secure? I want to trust you completely, and I need your support in getting there.",
        },
      ],
      reflection: "Jealousy often stems from insecurity. What boundaries or reassurances would help you both feel safer?",
    },
    miscommunication: {
      title: "Miscommunication",
      icon: "MessageSquareX" as const,
      steps: [
        {
          step: "Pause and reset",
          script: "I think we're misunderstanding each other. Can we start over and really listen to what each of us is trying to say?",
        },
        {
          step: "Clarify intent",
          script: "What I was trying to say is [your point]. But I'm hearing that you understood it as [their interpretation]. Is that right?",
        },
        {
          step: "Validate feelings",
          script: "I can see why you felt [emotion] when I said that. That wasn't my intention, and I'm sorry it came across that way.",
        },
        {
          step: "Find common ground",
          script: "What we both want is [common goal]. Let's focus on that instead of the confusion.",
        },
      ],
      reflection: "Miscommunication happens. The goal isn't to be perfect—it's to repair quickly and with care.",
    },
    stress: {
      title: "External Stress Affecting Relationship",
      icon: "CloudRain" as const,
      steps: [
        {
          step: "Acknowledge the stressor",
          script: "I know you're under a lot of stress with [work/family/etc.]. I want to support you, not add to it.",
        },
        {
          step: "Separate stress from relationship",
          script: "I'm noticing that the stress is affecting how we talk to each other. Can we acknowledge that and give each other some grace?",
        },
        {
          step: "Offer support",
          script: "How can I help lighten your load right now? Even if it's just being present and listening.",
        },
        {
          step: "Set boundaries",
          script: "Let's agree that when things get overwhelming, we'll check in with each other instead of shutting down or lashing out.",
        },
      ],
      reflection: "Stress is external, but how you handle it as a team defines your relationship.",
    },
    intimacy_mismatch: {
      title: "Intimacy Mismatch",
      icon: "HeartCrack" as const,
      steps: [
        {
          step: "Open with vulnerability",
          script: "I want to talk about our intimacy. I've been feeling [disconnected/frustrated/unsatisfied], and I want us to be on the same page.",
        },
        {
          step: "Share your needs",
          script: "For me, intimacy looks like [physical touch/quality time/deep conversations]. What does it look like for you?",
        },
        {
          step: "Listen without judgment",
          script: "I hear that you need [their preference]. Help me understand what that means to you and how we can meet in the middle.",
        },
        {
          step: "Create a plan",
          script: "Let's commit to [specific action] this week to reconnect. I want us to feel close again.",
        },
      ],
      reflection: "Intimacy isn't one-size-fits-all. Understanding each other's needs creates connection.",
    },
    unappreciated: {
      title: "Feeling Unappreciated",
      icon: "ThumbsDown" as const,
      steps: [
        {
          step: "Express your feelings",
          script: "I've been feeling like my efforts go unnoticed. I know you care, but I need to hear it more often.",
        },
        {
          step: "Give specific examples",
          script: "For example, when I [specific action], it would mean a lot to hear that you appreciate it.",
        },
        {
          step: "Understand their love language",
          script: "How do you prefer to show appreciation? Maybe we're expressing love differently and missing each other.",
        },
        {
          step: "Set expectations",
          script: "Can we make it a habit to acknowledge each other's efforts more? Even small thank-yous go a long way.",
        },
      ],
      reflection: "Everyone wants to feel valued. Make appreciation a daily habit, not a once-in-a-while gesture.",
    },
  },
};

export const SPARK_CHALLENGES = [
  {
    id: "eye-contact",
    title: "2-Minute Eye Contact",
    description: "Sit facing each other and maintain eye contact for 2 full minutes without speaking. Notice what emotions come up.",
    duration: "2 minutes",
    difficulty: "Medium",
    icon: "Eye" as const,
    benefit: "Deepens emotional connection and builds intimacy through vulnerability",
  },
  {
    id: "five-compliments",
    title: "5 Compliments Challenge",
    description: "Take turns giving each other 5 genuine, specific compliments. Go beyond physical appearance.",
    duration: "5 minutes",
    difficulty: "Easy",
    icon: "Heart" as const,
    benefit: "Boosts confidence and reminds you what you love about each other",
  },
  {
    id: "appreciation",
    title: "I Appreciate You Because...",
    description: "Complete this sentence 3 times: 'I appreciate you because...' Be specific about recent actions.",
    duration: "5 minutes",
    difficulty: "Easy",
    icon: "Star" as const,
    benefit: "Builds gratitude and makes your partner feel valued",
  },
  {
    id: "soft-question",
    title: "Tonight's Soft Question",
    description: "Ask a gentle, vulnerable question you've been thinking about. Create space for honest sharing.",
    duration: "10 minutes",
    difficulty: "Hard",
    icon: "MessageCircle" as const,
    benefit: "Opens doors to deeper conversations and emotional safety",
  },
  {
    id: "touch-meditation",
    title: "5-Minute Touch Meditation",
    description: "Hold hands or embrace in silence. Focus on your breathing and the feeling of being close.",
    duration: "5 minutes",
    difficulty: "Medium",
    icon: "Hand" as const,
    benefit: "Increases physical connection and oxytocin (bonding hormone)",
  },
  {
    id: "love-note",
    title: "Write a Love Note",
    description: "Write a short note expressing something you've been feeling but haven't said out loud.",
    duration: "10 minutes",
    difficulty: "Medium",
    icon: "PenLine" as const,
    benefit: "Helps articulate feelings and creates keepsakes of your love",
  },
  {
    id: "dance-together",
    title: "Slow Dance Together",
    description: "Put on a slow song and dance together in your living room. No talking, just movement.",
    duration: "One song",
    difficulty: "Easy",
    icon: "Music" as const,
    benefit: "Playful, romantic, and gets you physically close",
  },
  {
    id: "gratitude-exchange",
    title: "Daily Gratitude Exchange",
    description: "Share 3 things you're grateful for today, and 1 thing about your partner you're grateful for.",
    duration: "5 minutes",
    difficulty: "Easy",
    icon: "Sparkles" as const,
    benefit: "Shifts focus to positivity and strengthens appreciation",
  },
];
